/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e818fbd3b47458170c14e1fe806b2d80)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "SupportMCP";
	}
	interface Env {
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		MCP: DurableObjectNamespace<import("./src/server").SupportMCP>;
		TICKET_WORKFLOW: Workflow<Parameters<import("./src/server").TicketWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
